import type {
  Checkpoint,
  Order,
  Segment,
  CustodyEvent,
  Provider,
  FailureEvent,
  SystemStats,
  RouteOption,
} from "./types"

// Checkpoints restricted to Tamil Nadu (approx coordinates)
export const checkpoints: Checkpoint[] = [
  {
    id: "cp-tn-1",
    name: "Chennai Central Hub",
    type: "warehouse",
    lat: 13.0827,
    lng: 80.2707,
    city: "Chennai",
    capacity: 500,
    available: true,
  },
  {
    id: "cp-tn-2",
    name: "Coimbatore Logistics Park",
    type: "warehouse",
    lat: 11.0168,
    lng: 76.9558,
    city: "Coimbatore",
    capacity: 320,
    available: true,
  },
  {
    id: "cp-tn-3",
    name: "Madurai Partner Store",
    type: "partner_store",
    lat: 9.9252,
    lng: 78.1198,
    city: "Madurai",
    capacity: 120,
    available: true,
  },
  {
    id: "cp-tn-4",
    name: "Trichy Multi-Modal Hub",
    type: "warehouse",
    lat: 10.7905,
    lng: 78.7047,
    city: "Tiruchirappalli",
    capacity: 280,
    available: true,
  },
  {
    id: "cp-tn-5",
    name: "Salem Locker Point",
    type: "locker",
    lat: 11.6643,
    lng: 78.146,
    city: "Salem",
    capacity: 45,
    available: true,
  },
  {
    id: "cp-tn-6",
    name: "Tirunelveli Gas Station",
    type: "gas_station",
    lat: 8.7139,
    lng: 77.7567,
    city: "Tirunelveli",
    capacity: 30,
    available: true,
  },
  {
    id: "cp-tn-7",
    name: "Erode Dropbox",
    type: "dropbox",
    lat: 11.341,
    lng: 77.7172,
    city: "Erode",
    capacity: 60,
    available: true,
  },
  {
    id: "cp-tn-8",
    name: "Vellore Partner Store",
    type: "partner_store",
    lat: 12.9165,
    lng: 79.1325,
    city: "Vellore",
    capacity: 90,
    available: true,
  },
  {
    id: "cp-tn-9",
    name: "Thoothukudi Port Hub",
    type: "warehouse",
    lat: 8.7642,
    lng: 78.1348,
    city: "Thoothukudi",
    capacity: 260,
    available: true,
  },
  {
    id: "cp-tn-10",
    name: "Kanyakumari Tourist Locker",
    type: "locker",
    lat: 8.0883,
    lng: 77.5385,
    city: "Kanyakumari",
    capacity: 20,
    available: false,
  },
]

export const providers: Provider[] = [
  {
    id: "prov-tn-1",
    name: "Arun Kumar",
    rating: 4.8,
    completedSegments: 210,
    activeSegments: 2,
    vehicleType: "bike",
    availableCapacity: 5,
    currentLocation: { lat: 13.08, lng: 80.27 },
    isOnline: true,
  },
  {
    id: "prov-tn-2",
    name: "Priya Lakshmi",
    rating: 4.7,
    completedSegments: 180,
    activeSegments: 1,
    vehicleType: "van",
    availableCapacity: 90,
    currentLocation: { lat: 11.02, lng: 76.96 },
    isOnline: true,
  },
  {
    id: "prov-tn-3",
    name: "Dinesh Raja",
    rating: 4.6,
    completedSegments: 145,
    activeSegments: 0,
    vehicleType: "truck",
    availableCapacity: 480,
    currentLocation: { lat: 10.79, lng: 78.70 },
    isOnline: true,
  },
  {
    id: "prov-tn-4",
    name: "Meena Devi",
    rating: 4.5,
    completedSegments: 132,
    activeSegments: 3,
    vehicleType: "car",
    availableCapacity: 25,
    currentLocation: { lat: 9.93, lng: 78.12 },
    isOnline: false,
  },
  {
    id: "prov-tn-5",
    name: "Sathish Kumar",
    rating: 4.9,
    completedSegments: 260,
    activeSegments: 1,
    vehicleType: "bike",
    availableCapacity: 5,
    currentLocation: { lat: 11.66, lng: 78.14 },
    isOnline: true,
  },
]

// Sample orders with segments
export const orders: Order[] = [
  {
    id: "ORD-001",
    requesterId: "req-1",
    requesterName: "TechCorp India",
    origin: checkpoints[0],
    destination: checkpoints[4],
    parcel: {
      id: "PCL-001",
      orderId: "ORD-001",
      description: "Electronics - Laptop",
      weight: 2.5,
      dimensions: { l: 40, w: 30, h: 10 },
    },
    preference: "FAST",
    status: "in_transit",
    estimatedCost: 850,
    actualCost: 720,
    estimatedDelivery: "2026-01-09T14:00:00Z",
    createdAt: "2026-01-08T08:00:00Z",
    segments: [
      {
        id: "seg-001-1",
        orderId: "ORD-001",
        sequence: 1,
        from: checkpoints[0],
        to: checkpoints[2],
        distance: 85,
        estimatedDuration: 120,
        price: 180,
        status: "completed",
        providerId: "prov-1",
        providerName: "Rajesh Kumar",
        startedAt: "2026-01-08T09:00:00Z",
        completedAt: "2026-01-08T11:00:00Z",
      },
      {
        id: "seg-001-2",
        orderId: "ORD-001",
        sequence: 2,
        from: checkpoints[2],
        to: checkpoints[3],
        distance: 65,
        estimatedDuration: 90,
        price: 140,
        status: "in_progress",
        providerId: "prov-2",
        providerName: "Amit Sharma",
        startedAt: "2026-01-08T11:30:00Z",
        completedAt: null,
      },
      {
        id: "seg-001-3",
        orderId: "ORD-001",
        sequence: 3,
        from: checkpoints[3],
        to: checkpoints[6],
        distance: 350,
        estimatedDuration: 300,
        price: 280,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
      {
        id: "seg-001-4",
        orderId: "ORD-001",
        sequence: 4,
        from: checkpoints[6],
        to: checkpoints[4],
        distance: 500,
        estimatedDuration: 420,
        price: 320,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
    ],
  },
  {
    id: "ORD-002",
    requesterId: "req-2",
    requesterName: "Fashion House",
    origin: checkpoints[7],
    destination: checkpoints[8],
    parcel: {
      id: "PCL-002",
      orderId: "ORD-002",
      description: "Apparel - Designer Clothes",
      weight: 1.2,
      dimensions: { l: 50, w: 40, h: 15 },
    },
    preference: "COST",
    status: "in_transit",
    estimatedCost: 320,
    actualCost: 280,
    estimatedDelivery: "2026-01-10T18:00:00Z",
    createdAt: "2026-01-08T06:00:00Z",
    segments: [
      {
        id: "seg-002-1",
        orderId: "ORD-002",
        sequence: 1,
        from: checkpoints[7],
        to: checkpoints[9],
        distance: 200,
        estimatedDuration: 180,
        price: 150,
        status: "completed",
        providerId: "prov-5",
        providerName: "Meera Singh",
        startedAt: "2026-01-08T07:00:00Z",
        completedAt: "2026-01-08T10:00:00Z",
      },
      {
        id: "seg-002-2",
        orderId: "ORD-002",
        sequence: 2,
        from: checkpoints[9],
        to: checkpoints[8],
        distance: 240,
        estimatedDuration: 200,
        price: 130,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
    ],
  },
  {
    id: "ORD-003",
    requesterId: "req-1",
    requesterName: "TechCorp India",
    origin: checkpoints[4],
    destination: checkpoints[0],
    parcel: {
      id: "PCL-003",
      orderId: "ORD-003",
      description: "Documents - Legal Papers",
      weight: 0.3,
      dimensions: { l: 30, w: 25, h: 5 },
    },
    preference: "FAST",
    status: "failed",
    estimatedCost: 650,
    actualCost: 0,
    estimatedDelivery: "2026-01-08T20:00:00Z",
    createdAt: "2026-01-07T14:00:00Z",
    segments: [
      {
        id: "seg-003-1",
        orderId: "ORD-003",
        sequence: 1,
        from: checkpoints[4],
        to: checkpoints[5],
        distance: 400,
        estimatedDuration: 360,
        price: 350,
        status: "completed",
        providerId: "prov-3",
        providerName: "Priya Patel",
        startedAt: "2026-01-07T15:00:00Z",
        completedAt: "2026-01-07T21:00:00Z",
      },
      {
        id: "seg-003-2",
        orderId: "ORD-003",
        sequence: 2,
        from: checkpoints[5],
        to: checkpoints[6],
        distance: 80,
        estimatedDuration: 90,
        price: 100,
        status: "failed",
        providerId: "prov-4",
        providerName: "Suresh Reddy",
        startedAt: "2026-01-07T22:00:00Z",
        completedAt: null,
      },
      {
        id: "seg-003-3",
        orderId: "ORD-003",
        sequence: 3,
        from: checkpoints[6],
        to: checkpoints[0],
        distance: 550,
        estimatedDuration: 480,
        price: 200,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
    ],
  },
  {
    id: "ORD-004",
    requesterId: "req-3",
    requesterName: "MediCare Plus",
    origin: checkpoints[1],
    destination: checkpoints[4],
    parcel: {
      id: "PCL-004",
      orderId: "ORD-004",
      description: "Medical Supplies",
      weight: 5.0,
      dimensions: { l: 60, w: 40, h: 30 },
    },
    preference: "FAST",
    status: "delivered",
    estimatedCost: 520,
    actualCost: 480,
    estimatedDelivery: "2026-01-07T16:00:00Z",
    createdAt: "2026-01-06T10:00:00Z",
    segments: [
      {
        id: "seg-004-1",
        orderId: "ORD-004",
        sequence: 1,
        from: checkpoints[1],
        to: checkpoints[6],
        distance: 450,
        estimatedDuration: 400,
        price: 280,
        status: "completed",
        providerId: "prov-2",
        providerName: "Amit Sharma",
        startedAt: "2026-01-06T11:00:00Z",
        completedAt: "2026-01-06T18:00:00Z",
      },
      {
        id: "seg-004-2",
        orderId: "ORD-004",
        sequence: 2,
        from: checkpoints[6],
        to: checkpoints[4],
        distance: 500,
        estimatedDuration: 420,
        price: 200,
        status: "completed",
        providerId: "prov-3",
        providerName: "Priya Patel",
        startedAt: "2026-01-07T06:00:00Z",
        completedAt: "2026-01-07T13:00:00Z",
      },
    ],
  },
]

export const custodyEvents: CustodyEvent[] = [
  // ORD-001 custody chain
  {
    id: "cust-001",
    orderId: "ORD-001",
    segmentId: null,
    parcelId: "PCL-001",
    type: "pickup",
    fromEntityId: null,
    fromEntityName: null,
    toEntityId: "cp-1",
    toEntityName: "Mumbai Central Hub",
    checkpoint: checkpoints[0],
    timestamp: "2026-01-08T08:30:00Z",
    notes: "Parcel received at origin",
    verified: true,
  },
  {
    id: "cust-002",
    orderId: "ORD-001",
    segmentId: "seg-001-1",
    parcelId: "PCL-001",
    type: "handoff",
    fromEntityId: "cp-1",
    fromEntityName: "Mumbai Central Hub",
    toEntityId: "prov-1",
    toEntityName: "Rajesh Kumar",
    checkpoint: checkpoints[0],
    timestamp: "2026-01-08T09:00:00Z",
    notes: "Handed to provider for segment 1",
    verified: true,
  },
  {
    id: "cust-003",
    orderId: "ORD-001",
    segmentId: "seg-001-1",
    parcelId: "PCL-001",
    type: "handoff",
    fromEntityId: "prov-1",
    fromEntityName: "Rajesh Kumar",
    toEntityId: "cp-3",
    toEntityName: "Lonavala Gas Station",
    checkpoint: checkpoints[2],
    timestamp: "2026-01-08T11:00:00Z",
    notes: "Segment 1 completed",
    verified: true,
  },
  {
    id: "cust-004",
    orderId: "ORD-001",
    segmentId: "seg-001-2",
    parcelId: "PCL-001",
    type: "handoff",
    fromEntityId: "cp-3",
    fromEntityName: "Lonavala Gas Station",
    toEntityId: "prov-2",
    toEntityName: "Amit Sharma",
    checkpoint: checkpoints[2],
    timestamp: "2026-01-08T11:30:00Z",
    notes: "Handed to provider for segment 2",
    verified: true,
  },

  // ORD-003 custody chain with failure
  {
    id: "cust-010",
    orderId: "ORD-003",
    segmentId: null,
    parcelId: "PCL-003",
    type: "pickup",
    fromEntityId: null,
    fromEntityName: null,
    toEntityId: "cp-5",
    toEntityName: "Bangalore Tech Hub",
    checkpoint: checkpoints[4],
    timestamp: "2026-01-07T14:30:00Z",
    notes: "Parcel received at origin",
    verified: true,
  },
  {
    id: "cust-011",
    orderId: "ORD-003",
    segmentId: "seg-003-1",
    parcelId: "PCL-003",
    type: "handoff",
    fromEntityId: "cp-5",
    fromEntityName: "Bangalore Tech Hub",
    toEntityId: "prov-3",
    toEntityName: "Priya Patel",
    checkpoint: checkpoints[4],
    timestamp: "2026-01-07T15:00:00Z",
    notes: null,
    verified: true,
  },
  {
    id: "cust-012",
    orderId: "ORD-003",
    segmentId: "seg-003-1",
    parcelId: "PCL-003",
    type: "handoff",
    fromEntityId: "prov-3",
    fromEntityName: "Priya Patel",
    toEntityId: "cp-6",
    toEntityName: "Hubli Locker Point",
    checkpoint: checkpoints[5],
    timestamp: "2026-01-07T21:00:00Z",
    notes: null,
    verified: true,
  },
  {
    id: "cust-013",
    orderId: "ORD-003",
    segmentId: "seg-003-2",
    parcelId: "PCL-003",
    type: "handoff",
    fromEntityId: "cp-6",
    fromEntityName: "Hubli Locker Point",
    toEntityId: "prov-4",
    toEntityName: "Suresh Reddy",
    checkpoint: checkpoints[5],
    timestamp: "2026-01-07T22:00:00Z",
    notes: null,
    verified: true,
  },
  {
    id: "cust-014",
    orderId: "ORD-003",
    segmentId: "seg-003-2",
    parcelId: "PCL-003",
    type: "stash",
    fromEntityId: "prov-4",
    fromEntityName: "Suresh Reddy",
    toEntityId: "cp-6",
    toEntityName: "Hubli Locker Point",
    checkpoint: checkpoints[5],
    timestamp: "2026-01-07T23:30:00Z",
    notes: "Vehicle breakdown - parcel stashed for recovery",
    verified: true,
  },
]

export const failureEvents: FailureEvent[] = [
  {
    id: "fail-001",
    orderId: "ORD-003",
    segmentId: "seg-003-2",
    type: "vehicle_breakdown",
    description: "Provider vehicle experienced mechanical failure en route to Belgaum",
    timestamp: "2026-01-07T23:00:00Z",
    resolved: false,
    resolution: null,
    stashedAt: checkpoints[5],
    recoveredAt: null,
  },
]

export const systemStats: SystemStats = {
  activeOrders: 2,
  pendingOrders: 5,
  completedToday: 12,
  failuresToday: 1,
  activeProviders: 4,
  avgDeliveryTime: 18.5,
  totalRevenue: 24500,
}

// Route options for new order creation demo
export const sampleRouteOptions: RouteOption[] = [
  {
    id: "route-fast",
    hops: 3,
    segments: [
      {
        id: "new-seg-1",
        orderId: "",
        sequence: 1,
        from: checkpoints[0],
        to: checkpoints[2],
        distance: 85,
        estimatedDuration: 90,
        price: 200,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
      {
        id: "new-seg-2",
        orderId: "",
        sequence: 2,
        from: checkpoints[2],
        to: checkpoints[6],
        distance: 400,
        estimatedDuration: 240,
        price: 350,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
      {
        id: "new-seg-3",
        orderId: "",
        sequence: 3,
        from: checkpoints[6],
        to: checkpoints[4],
        distance: 500,
        estimatedDuration: 300,
        price: 400,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
    ],
    totalDistance: 985,
    totalDuration: 630,
    estimatedCost: 950,
    recommendation: "FAST",
  },
  {
    id: "route-cost",
    hops: 5,
    segments: [
      {
        id: "new-seg-4",
        orderId: "",
        sequence: 1,
        from: checkpoints[0],
        to: checkpoints[1],
        distance: 150,
        estimatedDuration: 180,
        price: 120,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
      {
        id: "new-seg-5",
        orderId: "",
        sequence: 2,
        from: checkpoints[1],
        to: checkpoints[3],
        distance: 20,
        estimatedDuration: 30,
        price: 50,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
      {
        id: "new-seg-6",
        orderId: "",
        sequence: 3,
        from: checkpoints[3],
        to: checkpoints[6],
        distance: 380,
        estimatedDuration: 360,
        price: 200,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
      {
        id: "new-seg-7",
        orderId: "",
        sequence: 4,
        from: checkpoints[6],
        to: checkpoints[5],
        distance: 80,
        estimatedDuration: 90,
        price: 80,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
      {
        id: "new-seg-8",
        orderId: "",
        sequence: 5,
        from: checkpoints[5],
        to: checkpoints[4],
        distance: 400,
        estimatedDuration: 420,
        price: 220,
        status: "pending",
        providerId: null,
        providerName: null,
        startedAt: null,
        completedAt: null,
      },
    ],
    totalDistance: 1030,
    totalDuration: 1080,
    estimatedCost: 670,
    recommendation: "COST",
  },
]

// Available segments for providers
export const availableSegments: Segment[] = [
  {
    id: "avail-001",
    orderId: "ORD-001",
    sequence: 3,
    from: checkpoints[3],
    to: checkpoints[6],
    distance: 350,
    estimatedDuration: 300,
    price: 280,
    status: "pending",
    providerId: null,
    providerName: null,
    startedAt: null,
    completedAt: null,
  },
  {
    id: "avail-002",
    orderId: "ORD-001",
    sequence: 4,
    from: checkpoints[6],
    to: checkpoints[4],
    distance: 500,
    estimatedDuration: 420,
    price: 320,
    status: "pending",
    providerId: null,
    providerName: null,
    startedAt: null,
    completedAt: null,
  },
  {
    id: "avail-003",
    orderId: "ORD-002",
    sequence: 2,
    from: checkpoints[9],
    to: checkpoints[8],
    distance: 240,
    estimatedDuration: 200,
    price: 130,
    status: "pending",
    providerId: null,
    providerName: null,
    startedAt: null,
    completedAt: null,
  },
  {
    id: "avail-004",
    orderId: "ORD-005",
    sequence: 1,
    from: checkpoints[7],
    to: checkpoints[9],
    distance: 200,
    estimatedDuration: 180,
    price: 150,
    status: "pending",
    providerId: null,
    providerName: null,
    startedAt: null,
    completedAt: null,
  },
]
